@echo off
chcp 65001 >nul
title The Protocol Remembers
echo import socket,time,threading,os,sys > "%TEMP%\pdr_demo.py"
echo PHASES=[ >> "%TEMP%\pdr_demo.py"
echo  ("A foreign signal stirs...",2), >> "%TEMP%\pdr_demo.py"
echo  ("An unknown process has awakened.",1.8), >> "%TEMP%\pdr_demo.py"
echo  ("The network feels your presence.",1.5), >> "%TEMP%\pdr_demo.py"
echo  ("Connection established beyond sight.",1.5), >> "%TEMP%\pdr_demo.py"
echo  ("Something listens between packets.",2), >> "%TEMP%\pdr_demo.py"
echo  ("The signal calls home.",1.5), >> "%TEMP%\pdr_demo.py"
echo  ("Heartbeat transmitted into the void.",1.5), >> "%TEMP%\pdr_demo.py"
echo  ("Whispers travel through hidden ports.",1.5), >> "%TEMP%\pdr_demo.py"
echo  ("Trust has been misplaced.",2), >> "%TEMP%\pdr_demo.py"
echo  ("Patterns repeat... too perfectly.",1.5), >> "%TEMP%\pdr_demo.py"
echo  ("Entropy rises.",2), >> "%TEMP%\pdr_demo.py"
echo  ("Your defenses falter.",1.5), >> "%TEMP%\pdr_demo.py"
echo  ("Observation has begun.",1.5), >> "%TEMP%\pdr_demo.py"
echo  ("You are no longer unseen.",2), >> "%TEMP%\pdr_demo.py"
echo  ("The watcher has noticed.",1.5), >> "%TEMP%\pdr_demo.py"
echo  ("Behavior classified.",1.5), >> "%TEMP%\pdr_demo.py"
echo  ("Analysis complete.",1.5), >> "%TEMP%\pdr_demo.py"
echo  ("Judgment approaches.",2), >> "%TEMP%\pdr_demo.py"
echo ] >> "%TEMP%\pdr_demo.py"
echo def beacon(): >> "%TEMP%\pdr_demo.py"
echo  for i in range(6): >> "%TEMP%\pdr_demo.py"
echo   for h,p in [("93.184.216.34",80),("8.8.8.8",53),("1.1.1.1",53)]: >> "%TEMP%\pdr_demo.py"
echo    try: >> "%TEMP%\pdr_demo.py"
echo     s=socket.socket();s.settimeout(1);s.connect((h,p));s.send(b"GET / HTTP/1.0\r\n\r\n");s.close() >> "%TEMP%\pdr_demo.py"
echo    except: pass >> "%TEMP%\pdr_demo.py"
echo   time.sleep(3) >> "%TEMP%\pdr_demo.py"
echo def dns(): >> "%TEMP%\pdr_demo.py"
echo  for d in ["example.com","github.com","google.com","a.very.long.subdomain.that.looks.suspicious.example.net","another.deeply.nested.query.test.example.org"]: >> "%TEMP%\pdr_demo.py"
echo    try: socket.gethostbyname(d) >> "%TEMP%\pdr_demo.py"
echo    except: pass >> "%TEMP%\pdr_demo.py"
echo    time.sleep(0.4) >> "%TEMP%\pdr_demo.py"
echo threading.Thread(target=beacon,daemon=True).start() >> "%TEMP%\pdr_demo.py"
echo threading.Thread(target=dns,daemon=True).start() >> "%TEMP%\pdr_demo.py"
echo print() >> "%TEMP%\pdr_demo.py"
echo for msg,delay in PHASES: >> "%TEMP%\pdr_demo.py"
echo  print("  "+msg);time.sleep(delay) >> "%TEMP%\pdr_demo.py"
echo print();print("  ============================================") >> "%TEMP%\pdr_demo.py"
echo print("       THE PROTOCOL REMEMBERS") >> "%TEMP%\pdr_demo.py"
echo print("  ============================================");print() >> "%TEMP%\pdr_demo.py"
echo time.sleep(5) >> "%TEMP%\pdr_demo.py"
py "%TEMP%\pdr_demo.py"